from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Text, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base

class Roadmap(Base):
    __tablename__ = "roadmaps"

    id = Column(Integer, primary_key=True, index=True)
    project_title = Column(String, index=True)
    goal = Column(String)
    level = Column(String)
    duration = Column(Integer)
    frequency = Column(String)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    missions = relationship("Mission", back_populates="roadmap", cascade="all, delete-orphan")
    chats = relationship("ChatHistory", back_populates="roadmap", cascade="all, delete-orphan")

class Mission(Base):
    __tablename__ = "missions"

    id = Column(Integer, primary_key=True, index=True)
    roadmap_id = Column(Integer, ForeignKey("roadmaps.id"))
    week = Column(Integer)
    theme = Column(String)
    mission_key = Column(String)  # e.g., "w1_m1"
    title = Column(String)
    is_completed = Column(Boolean, default=False)

    # Relationships
    roadmap = relationship("Roadmap", back_populates="missions")

class ChatHistory(Base):
    __tablename__ = "chat_history"

    id = Column(Integer, primary_key=True, index=True)
    roadmap_id = Column(Integer, ForeignKey("roadmaps.id"))
    role = Column(String)  # "user" or "model"
    text = Column(Text)
    image = Column(Text, nullable=True)  # Base64 string or URL (optional)
    model_image = Column(Text, nullable=True)  # Image generated by model (optional)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    roadmap = relationship("Roadmap", back_populates="chats")
